==== Alex Spaulding
[cols="1a,1a", options="header", frame=none, grid=none]
|====
| Missoula, MT | 406-240-9534
| aspauldingcode@gmail.com | https://linkedin.com/in/aspauldingcode
|====

===== ASPIRING COMPUTER SCIENCE INTERN
Disciplined and motivated computer science sophomore with a strong interest in web development, data engineering, and project management. Proficient in:
* **Software Engineering:** Java, Python, JavaScript, TypeScript
* **Version Control & Collaboration:** GIT Operations / Workflow
* **Web Frameworks & Libraries:** React.JS, Django, Flutter, Framer Motion
* **Customer Relationship Management (CRM):** TeamDynamix, Zendesk, Salesforce (Trailhead)

===== EDUCATION
* **Bachelor of Science (BS) in Computer Science**  
  *Data Science Concentration - Mathematics Minor*  
  University of Montana | Expected May 2026  
  *Computer Science Club member & Cybersecurity Club member*
* **Front-end Developer Certification**  
  *18-week program*  
  Montana Code School / Promineo Tech, Missoula, MT | 2020

===== PROFESSIONAL EXPERIENCE
====== IT Consultant
*University of Montana IT Help Desk, Missoula, MT*  
*(Sep 2020 - Oct 2020) | (Oct 2024 - Present)*  
- Provide Tier I phone support, resolving support tickets on TeamDynamix related to logins, laptops, printers, internet issues, software, account setup, and technical configuration.
- Conduct weekly sprints to deliver on-site technical support to students and employees.

====== PCB Technician
*Sunburst Sensors, Missoula, MT*  
*(Jan 2022 - Present)*  
- Design and manufacture autonomous instruments measuring marine and freshwater inorganic carbon parameters (CO2 and pH) using patented drift-free technology.
- Solder components to printed circuit boards (PCB), craft cabling, adapters, and battery packs to facilitate product shipping and power provision.

====== Sales Associate – Seasonal
*Men's Wearhouse, Missoula, MT*  
*(Jun 2023 - Aug 2023)*  
- Sized customers and sold tuxedos, suits, sport jackets, and wedding rentals.
- Utilized strong sales skills to ensure every customer left with a purchase, whether it was a suit, shirt, or accessory, enhancing their shopping experience.

====== Apple Sales – Seasonal
*Simply Mac, Missoula, MT*  
*(Oct 2018 - Nov 2018)*  
- Welcomed and assisted customers with professional support, sales, service, and phone repair.
- Exceeded monthly sales quotas for Macs, MacBook Pros, iPads, and new/used MacBooks.

====== Web Developer
*Wheelbound Productions, Missoula, MT*  
*(Apr 2018 - Sep 2018)*  
- Provided personalized customer service to discuss business plans and website goals, resulting in the design of mobile-friendly dynamic websites.
- Utilized JavaScript to create engaging homepages featuring multi-parallax scrolling, animations, and interactive elements.

====== SKILLSET
* **Front-end Development Skills:**  
  JavaScript, ReactJS, Webpack, Bootstrap, Object-Oriented Programming (OOP), Design Patterns, Databases, HTML, CSS, jQuery, AJAX, REST
* **Additional Programming Skills:**  
  Paradigms, Create-Read-Update-Delete (CRUD) Applications, Amazon Web Services (AWS), SQL, GIT, API, SaaS Applications
