==== *Alex Spaulding*
[cols="1a,1a", options="header", frame=none, grid=none]
|====
| Spokane, WA | 406-240-9534
| aspauldingcode@gmail.com | https://linkedin.com/in/aspauldingcode
| https://aspauldingcode.com | Portfolio
|====

===== *ASPIRING SOFTWARE ENGINEER*
Disciplined and motivated computer science Junior with a strong interest in operating systems and project management. Extensive experience in reverse engineering. Proficient in:

// Order based on popularity. Focus on readability. Focus on the most relevant skills from the intern/job application. //
[cols="1a,1a", frame=none, grid=none]
|====
| *Languages:* Python, JavaScript, Java, TypeScript, Rust, Swift, Objective-C, Nix |
| *Web:* Next.js, React, Django, Spring Boot |
| *Tools:* Git, AWS, Azure, SQL, REST APIs, CMake, CI/CD |
| *Reverse Engineering:* IDA Pro, C++, C, Objective-C, Private macOS Frameworks |
|====

===== *EDUCATION*
====== Bachelor of Science (BS) in Computer Science
_Eastern Washington University | Expected May 2027_

* Mathematics Minor
* Active member of Computer Science and Cybersecurity Clubs

====== Front-end Developer Certification
_Montana Code School / Promineo Tech, Missoula, MT | 2020_

* Completed intensive 18-week program focused on web development

===== *PROFESSIONAL EXPERIENCE*
====== Information Technology (IT) Consultant
_University of Montana IT Help Desk, Missoula, MT_
_(Sep 2020 - Oct 2020) | (Oct 2024 - Jan 2025)_

* Provide Tier I phone support, resolving support tickets on TeamDynamix related to logins, laptops, printers, internet issues, software, account setup, and technical configuration
* Conduct weekly sprints to deliver on-site technical support to students and employees
* Implement and maintain automated system monitoring solutions

====== Printed Circuit Board (PCB) Technician
_Sunburst Sensors, Missoula, MT_
_(Jan 2022 - Mar 2025)_

* Design and manufacture autonomous instruments measuring marine and freshwater inorganic carbon parameters (CO2 and pH) using patented drift-free technology
* Solder components to printed circuit boards (PCB), craft cabling, adapters, and battery packs to facilitate product shipping and power provision
* Optimize sensor calibration using statistical techniques

====== Sales Associate – Seasonal
_Men's Wearhouse, Missoula, MT_
_(Jun 2023 - Aug 2023)_

* Sized customers and sold tuxedos, suits, sport jackets, and wedding rentals
* Utilized strong sales skills to ensure every customer left with a purchase, whether it was a suit, shirt, or accessory, enhancing their shopping experience
* Utilized data-driven approaches to optimize sales strategies

====== Apple Sales – Seasonal
_Simply Mac, Missoula, MT_
_(Oct 2018 - Nov 2018)_

* Welcomed and assisted customers with professional support, sales, service, and phone repair
* Exceeded monthly sales quotas for Macs, MacBook Pros, iPads, and new/used MacBooks
* Provided technical support for applications and features

====== Web Developer
_Wheelbound Productions, Missoula, MT_
_(Apr 2018 - Sep 2018)_

* Provided personalized customer service to discuss business plans and website goals, resulting in the design of mobile-friendly dynamic websites
* Utilized JavaScript, HTML, CSS, and SASS to create engaging homepages featuring multi-parallax scrolling, animations, and interactive elements
* Integrated chat support and SEO optimization tools to enhance user engagement and search rankings

// Add skills from the intern/job application. //
===== *SKILLSET*
|===
|Category |Skills

|Data Science & Analytics
|Statistical Analysis +
Data Visualization +
Big Data Processing

|Back-end Development
|Python, Java +
REST APIs, SQL Databases +
CRUD Applications +
AWS Cloud Services +
SaaS Architecture, Rust

|Automation
|Shell Scripting (POSIX) +
Nix Build/Dev Automation +
Automation Scripts +
AppleScript

|Systems & Low-level Programming
|Reverse Engineering +
Operating Systems Development +
Kernel Programming +
Assembly Language +
System Architecture

|Development Tools & Paradigms
|Object-Oriented Programming (OOP) +
Design Patterns +
Webpack +
Swift, Objective-C +
Nix

|Front-end Development
|JavaScript, TypeScript, NextJS, +
ReactJS, HTML, CSS, Bootstrap +
Responsive Design +
AJAX, jQuery +
Web Animations

|Version Control & Collaboration
|Git +
API Documentation +
TeamDynamix +
AsciiDoc Documentation +
Github Actions +
Open Source Software contributions

|Content Creation
|Graphics Design +
Adobe Photoshop, Blender +
Adobe Premier Pro +
Music Production (Ableton Live, Logic Pro) +
YouTube Content Creation +
|===

===== *REFERENCES*
_For references, please contact me._

// [cols="1a,1a", frame=none, grid=none]
// |====
// | Jane Doe | janedoe@example.com
// |====

